[[annex-A]]
[appendix, obligation=normative]
== Abstract Test Suite

=== Introduction

GeoPose 1.1 specifies eight Standardization Targets using elements of the Logical Model. These elements are Structural Data Units (SDUs) and they have the stereotype "Structural Data Unit - SDU". Each SDU is an element of the Logical Model that will be expressed in concrete data objects encoded using specific encoding or serialization technologies.

Implementation of the eight Standardization Targets is independent of the GeoPose Logical Model. The implementation of GeoPose 1.1 is neutral with regards to a developer's choice of encoding. To keep the individual Standardization targets independent, there are some SDU requirements and corresponding conformance tests that appear in more than one requirement or conformance class. This structure is based on the judgement that it is easier to understand the independence of targets with complete definitions than would be the case if the definitional requirements of the SDUs were factored out and referenced indirectly by individual encodings.


=== Global conformance class

Conformance with the Global Requirements is required for all implementations.

[yaml2text,modspec/yaml/global-cc.yaml,group]
----
{% assign prefix = "global" %}
include::modspec/conformance_class.liquid[]
----

=== Common conformance classes

==== Tangent point specification conformance class

[yaml2text,modspec/yaml/tangent-point-cc.yaml,group]
----
{% assign prefix = "tangent-point" %}
include::modspec/conformance_class.liquid[]
----

==== Frame specification conformance class

[yaml2text,modspec/yaml/frame-spec-cc.yaml,group]
----
{% assign prefix = "frame-spec" %}
include::modspec/conformance_class.liquid[]
----

==== Time specification conformance class

[yaml2text,modspec/yaml/time-cc.yaml,group]
----
{% assign prefix = "time" %}
include::modspec/conformance_class.liquid[]
----


=== SDU conformance

==== General

There are some universal requirements on values that appear in a concrete implementation using a specific encoding technology. For example, angles may be constrained to fall within a range of values corresponding to a circle. Because these are independent of encoding technology, they are specified here at a logical level. Tests of an implementation at the SDU level generally only be done by inspection.

==== Basic-YPR SDU Conformance Class

[yaml2text,modspec/yaml/basic-ypr-cc.yaml,group]
----
{% assign prefix = "basic-ypr" %}
include::modspec/conformance_class.liquid[]
----

==== Basic-Quaternion SDU Conformance Class

[yaml2text,modspec/yaml/basic-quaternion-cc.yaml,group]
----
{% assign prefix = "basic-quaternion" %}
include::modspec/conformance_class.liquid[]
----


==== Advanced SDU Conformance Class

[yaml2text,modspec/yaml/advanced-cc.yaml,group]
----
{% assign prefix = "advanced" %}
include::modspec/conformance_class.liquid[]
----



==== Graph SDU Conformance Class

[yaml2text,modspec/yaml/graph-cc.yaml,group]
----
{% assign prefix = "graph" %}
include::modspec/conformance_class.liquid[]
----



==== Chain SDU Conformance Class

[yaml2text,modspec/yaml/chain-cc.yaml,group]
----
{% assign prefix = "chain" %}
include::modspec/conformance_class.liquid[]
----


==== Regular Series SDU Conformance Class

[yaml2text,modspec/yaml/series-regular-cc.yaml,group]
----
{% assign prefix = "series-regular" %}
include::modspec/conformance_class.liquid[]
----



==== Irregular Series SDU Conformance Class

[yaml2text,modspec/yaml/series-irregular-cc.yaml,group]
----
{% assign prefix = "series-irregular" %}
include::modspec/conformance_class.liquid[]
----



==== Stream SDU Conformance Class

[yaml2text,modspec/yaml/stream-cc.yaml,group]
----
{% assign prefix = "stream" %}
include::modspec/conformance_class.liquid[]
----



